### PR TITLE
Feat: frontend

### PR DESCRIPTION
**Pull request by Arbind007**

### CODE REVIEW

**Comment by gitaalekhyapaul** [comment]
Why is there a `requirements.txt` and `.DS_Store` file @Arbind007 ?
Try to update the `.gitignore` file

**Review by gitaalekhyapaul — CHANGES_REQUESTED** [review]
Homepage, Navbar, Footer components missing. Kindly commit all the components.

**Comment by Arbind007** [comment]
Bhai mera repo se utha la

**Review by gitaalekhyapaul — APPROVED** [review]
LGTM! :partying_face:

**Pull request merged**
